[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x354caaf9bd19f0a44a3d9301458f404fad4b676bd3f879c09b215c5ec66418b"
transaction_hash = "0x338bc7fe1984f2fe8aa8ada6a203bee5a23a4cf9222b98d914cc2b2ac132294"
block_number = 3
seed = "brewmaster"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "http://localhost:5050/"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x76f7bf89ee554e8e182be67600e006fc543339f6074d04ce5c86515525539bd"
class_hash = "0x7bfcece8b9fd12bf3db2b0c4c12e3a9bbc574870695de3470e567c3a4b2a297"
original_class_hash = "0x7bfcece8b9fd12bf3db2b0c4c12e3a9bbc574870695de3470e567c3a4b2a297"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/brewmaster_systems_actions_Brewmaster.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "brewmaster::systems::actions::Brewmaster"

[[models]]
kind = "DojoModel"
class_hash = "0x2d6a36bd1a77cacc61a29a32434bcf96a7924d99a6e775e87e9ee7382917c03"
original_class_hash = "0x2d6a36bd1a77cacc61a29a32434bcf96a7924d99a6e775e87e9ee7382917c03"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_brewpub_brew_pub_struct.json"
name = "brewmaster::models::brewpub::brew_pub_struct"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "scale"
type = "Array<PubScaleStruct>"
key = false

[[models.members]]
name = "treasury"
type = "u256"
key = false

[[models.members]]
name = "points"
type = "u256"
key = false

[[models.members]]
name = "createAt"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x73c5a825870828e8c900aca029a1d942dab512227f45623d1b94f884d42c6ee"
original_class_hash = "0x73c5a825870828e8c900aca029a1d942dab512227f45623d1b94f884d42c6ee"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_manager_signature.json"
name = "brewmaster::models::manager::manager_signature"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "msgHash"
type = "felt252"
key = false

[[models.members]]
name = "isUsed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x584818384c48945657bfbca5474e15f1b17403fdb80deff0acf9420e98e3419"
original_class_hash = "0x584818384c48945657bfbca5474e15f1b17403fdb80deff0acf9420e98e3419"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_max_scale.json"
name = "brewmaster::models::manager::max_scale"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "maxTable"
type = "u16"
key = false

[[models.members]]
name = "maxStool"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xbce3c2a10a161c193b067e63a899a9be4661f86be05a25f957498cc0708ce4"
original_class_hash = "0xbce3c2a10a161c193b067e63a899a9be4661f86be05a25f957498cc0708ce4"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_system_manager.json"
name = "brewmaster::models::manager::system_manager"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "managerAddress"
type = "ContractAddress"
key = false
