[world]
kind = "WorldContract"
class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
original_class_hash = "0x3f63cecdc4964acafb921ba2934c6507d1b3c344edb64c2762cf08053169ab9"
abi = "manifests/dev/abis/deployments/dojo_world_world.json"
address = "0x354caaf9bd19f0a44a3d9301458f404fad4b676bd3f879c09b215c5ec66418b"
transaction_hash = "0x35a8dbf9f79999d9ab8f6882673797a0db85e854f721caf985a115fea291dfd"
block_number = 743856
seed = "brewmaster"
name = "dojo::world::world"

[world.metadata]
profile_name = "dev"
rpc_url = "https://starknet-mainnet.public.blastapi.io/rpc/v0_7"

[base]
kind = "Class"
class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
original_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
name = "dojo::base::base"

[[contracts]]
kind = "DojoContract"
address = "0x76f7bf89ee554e8e182be67600e006fc543339f6074d04ce5c86515525539bd"
class_hash = "0x5264c6c0592736791c46c23f3de88acdc3e59e4c36b072a3f06647be324f107"
original_class_hash = "0x5264c6c0592736791c46c23f3de88acdc3e59e4c36b072a3f06647be324f107"
base_class_hash = "0x22f3e55b61d86c2ac5239fa3b3b8761f26b9a5c0b5f61ddbd5d756ced498b46"
abi = "manifests/dev/abis/deployments/contracts/brewmaster_systems_actions_Brewmaster.json"
reads = []
writes = []
computed = []
init_calldata = []
name = "brewmaster::systems::actions::Brewmaster"

[[models]]
kind = "DojoModel"
class_hash = "0x2d6a36bd1a77cacc61a29a32434bcf96a7924d99a6e775e87e9ee7382917c03"
original_class_hash = "0x2d6a36bd1a77cacc61a29a32434bcf96a7924d99a6e775e87e9ee7382917c03"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_brewpub_brew_pub_struct.json"
name = "brewmaster::models::brewpub::brew_pub_struct"

[[models.members]]
name = "player"
type = "ContractAddress"
key = true

[[models.members]]
name = "scale"
type = "Array<PubScaleStruct>"
key = false

[[models.members]]
name = "treasury"
type = "u256"
key = false

[[models.members]]
name = "points"
type = "u256"
key = false

[[models.members]]
name = "createAt"
type = "u64"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x40d168ceeb44cdc3a1451700be79170bb13f2229c2e36470eb1f03df86a643d"
original_class_hash = "0x40d168ceeb44cdc3a1451700be79170bb13f2229c2e36470eb1f03df86a643d"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_manager_signature.json"
name = "brewmaster::models::manager::manager_signature"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "msgHash"
type = "felt252"
key = true

[[models.members]]
name = "isUsed"
type = "bool"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x584818384c48945657bfbca5474e15f1b17403fdb80deff0acf9420e98e3419"
original_class_hash = "0x584818384c48945657bfbca5474e15f1b17403fdb80deff0acf9420e98e3419"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_max_scale.json"
name = "brewmaster::models::manager::max_scale"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "maxTable"
type = "u16"
key = false

[[models.members]]
name = "maxStool"
type = "u16"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0xbce3c2a10a161c193b067e63a899a9be4661f86be05a25f957498cc0708ce4"
original_class_hash = "0xbce3c2a10a161c193b067e63a899a9be4661f86be05a25f957498cc0708ce4"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_system_manager.json"
name = "brewmaster::models::manager::system_manager"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "managerAddress"
type = "ContractAddress"
key = false

[[models]]
kind = "DojoModel"
class_hash = "0x7c9c5ed91dc4e767434dd2a6ffb5c52cd14b486fb1d2a47579ba67de6ff69"
original_class_hash = "0x7c9c5ed91dc4e767434dd2a6ffb5c52cd14b486fb1d2a47579ba67de6ff69"
abi = "manifests/dev/abis/deployments/models/brewmaster_models_manager_upgrade_pub_price.json"
name = "brewmaster::models::manager::upgrade_pub_price"

[[models.members]]
name = "system"
type = "ContractAddress"
key = true

[[models.members]]
name = "addTablePrice"
type = "u256"
key = false

[[models.members]]
name = "addStoolPrice"
type = "u256"
key = false
